var yellow_line = [
    "finch", 
    "north-york-centre", 
    "york-mills", 
    "lawrence", 
    "eglinton", 
    "davisville", 
    "st-clair", 
    "summerhill",
    "rosedale",
    "bloor-yonge",
    "wellesley",
    "college",
    "dundas",
    "queen",
    "king",
    "union",
    "st-andrew",
    "osgoode",
    "st-patrick",
    "queens-park",
    "museum",
    "st-george",
    "spadina",
    "dupont",
    "st-clair-west",
    "eglinton-west",
    "glencarin",
    "lawrence-west",
    "yorkdale",
    "wilson",
    "downsview-park", //downsview_station//
];

var green_line = [
    "kipling",
    "islington",
    "royal-york",
    "old-mill",
    "jane",
    "runnymede",
    "high-park",
    "keele",
    "dundas-west",
    "landsdowne",
    "dufferin",
    "ossignton",
    "christie",
    "bathurst",
    "spadina",
    "st-george",
    "bay",
    "bloor_yonge",
    "sherbourne",
    "castle-frank",
    "broadview",
    "chester",
    "pape",
    "donlands",
    "greenwood",
    "coxwell",
    "woodbine",
    "main-street",
    "victoria-park",
    "warden",
    "kennedy"

];

var purple_line = [
    "bayview",
    "bessarion",
    "leslie",
    "don-mills"
];